// Mocks generated by Mockito 5.2.0 from annotations
// in mobile/test/wallpapers/search_wallpapers.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:mobile/main.dart' as _i4;
import 'package:mobile/repositories/wallpaper_repository.dart' as _i3;
import 'package:mobile/utils/constants.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

class _FakeInterceptorsWrapper_1 extends _i1.Fake
    implements _i2.InterceptorsWrapper {}

/// A class which mocks [WallPaperRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWallPaperRepository<T> extends _i1.Mock
    implements _i3.WallPaperRepository<T> {
  MockWallPaperRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(Invocation.setter(#dio, _dio),
      returnValueForMissingStub: null);
  @override
  _i4.CreatorCallback<dynamic> get creatorCallback =>
      (super.noSuchMethod(Invocation.getter(#creatorCallback),
              returnValue: (Map<String, dynamic> __p0) => null)
          as _i4.CreatorCallback<dynamic>);
  @override
  _i5.WallPaperProvider get wallPaperProvider =>
      (super.noSuchMethod(Invocation.getter(#wallPaperProvider),
          returnValue: _i5.WallPaperProvider.pexels) as _i5.WallPaperProvider);
  @override
  String get baseApiUrl =>
      (super.noSuchMethod(Invocation.getter(#baseApiUrl), returnValue: '')
          as String);
  @override
  _i2.InterceptorsWrapper interceptorsWrapper() => (super.noSuchMethod(
      Invocation.method(#interceptorsWrapper, []),
      returnValue: _FakeInterceptorsWrapper_1()) as _i2.InterceptorsWrapper);
  @override
  _i6.FutureOr<T> getItem(int? id,
          {Map<String, dynamic>? query = const {}}) =>
      (super.noSuchMethod(Invocation.method(#getItem, [id], {#query: query}),
          returnValue: Future<T>.value(null)) as _i6.FutureOr<T>);
  @override
  _i6.FutureOr<List<T>> getItems({Map<String, dynamic>? query = const {}}) =>
      (super.noSuchMethod(Invocation.method(#getItems, [], {#query: query}),
          returnValue: Future<List<T>>.value(<T>[])) as _i6.FutureOr<List<T>>);
  @override
  _i6.FutureOr<List<T>> searchItems({Map<String, dynamic>? query = const {}}) =>
      (super.noSuchMethod(Invocation.method(#searchItems, [], {#query: query}),
          returnValue: Future<List<T>>.value(<T>[])) as _i6.FutureOr<List<T>>);
}
